### ISSUE TITLE
[bug]: Flow Monitor Page displays error message constantly

### ISSUE THREAD

**Issue by Asterix7m** [flowsforapex/apex-flowsforapex#491] opened 2022-08-16 11:53 UTC
### Flows for APEX version

22.1 (latest release)

### Oracle Database version

19

### Oracle APEX version

21.2

### What happened?

The Flows Monitor display an error message. 
It is possible to use the Monitor after you have clicked OK on the error message. 
But the error message appears every time the page is re-displayed

![Screenshot from 2022-08-16 12-51-55](https://user-images.githubusercontent.com/96238749/184873207-550b0ae4-a1c7-4bb3-9812-807a6104ea82.png)
.

### Steps to reproduce

Not sure. Possibly related to do our workflow?

### Expected behaviour

No error message should be displayed

**Comment by commi235** [comment] 2022-08-16 12:02
Hi, can you attach an APEX debug log for reference?

**Comment by rallen2010** [comment] 2022-08-16 14:04
Or Feel free to email me at my oracle email address & I can arrange a phone or zoom call.  firstname.lastname at oracle.com

**Comment by Asterix7m** [comment] 2022-08-16 14:46
Hello Mortitz

The error doesnt seem to add anything to apex_debug_log.
I queried the log, then recreated the error. No new rows.

Thanks - Adam

**Comment by Asterix7m** [comment] 2022-08-16 14:47
Hi Richard

Happy to chat about this. What is your oracle address?
Alternatively feel free to call me on +44 7957 548686.

Thanks - Adam

**Comment by rallen2010** [comment] 2022-08-16 15:52
Problem was identified by using the model Linter in the Flow Diagrammer.  (Duplicate sequenceFlows linking the same objects).  Model now runs OK!  Closing as not a bug.

**Closed by rallen2010** 2022-08-16 15:52 UTC
Labels: not a bug
