### ISSUE TITLE
Business Process mining 

### ISSUE THREAD

**Issue by AbdulrhmanBashammmakh** [flowsforapex/apex-flowsforapex#505] opened 2022-09-04 04:31 UTC
Why is there no schedule for recording events for each process which thus helps to Process mining ?

Like  as Generate sql table  as logs event
To record activities.
- [enhancement]

**Comment by rallen2010** [comment] 2022-09-06 10:53
Closing this as a duplicate of #506

**Closed by rallen2010** 2022-09-06 10:53 UTC
