### ISSUE TITLE
[bug]: Timer opening in gateway

### ISSUE THREAD

**Issue by fahadrafique** [flowsforapex/apex-flowsforapex#440] opened 2022-03-07 11:39 UTC
### Flows for APEX version

22.1 (latest release)

### Oracle Database version

19

### Oracle APEX version

21.1

### What happened?

How to use timer which is opening in the gateway?
Sample is created on below link with the name "TIMER".
I didn't find documentation on such scenario.

https://apex.oracle.com/pls/apex/mtflows/r/flowsforapex/flow-management?session=2610576708456

### Steps to reproduce

N/A

### Expected behaviour

N/A

**Comment by rallen2010** [comment] 2022-03-07 14:28
HI,   The problem is that you haven't set any routing instructions for the gateway after the timer.
Your gateway is named Gateway_1yi27qd - so you need to set a process variable named Gateway_1yi27qd:route somewhere before you execute the gateway -- so that could be in your start event, in a Before-Task expression on your first task, or on a Before Split expression on the gateway.  
The value of the variable needs to be the ID of the sequenceFlow (the arrow!) that you want to take.  
So just to test it, I've added a Before Split Expression to your Gateway, that creates Gateway_1yi27qd:route and makes a static assignment of Flow_0xfrt38 to make it take the Low Priority route.
And it works fine, so I'm closing this as a Bug.

You can see a process instance called RJA-TimerTest that is set up & running nicely on your apex.oracle.com instance.
Hope this helps.  Richard.

**Closed by rallen2010** 2022-03-07 14:28 UTC
Labels: not a bug
