### ISSUE TITLE
[bug]: Existing Flows which are in failed status, throwing error when click on the error steps, however, it shows the exact error stack in earlier version. 

### ISSUE THREAD

**Issue by satyaOracle** [flowsforapex/apex-flowsforapex#454] opened 2022-04-27 09:35 UTC
### Flows for APEX version

22.1 (latest release)

### Oracle Database version

19

### Oracle APEX version

21.1

### What happened?

When any flow execution failed in any step and when that step clicked to show the error stack then getting the below error. Earlier version was showing the exact error.

"An unexpected internal application error has occurred. Please fill a bug at https://github.com/flowsforapex/apex-flowsforapex/issues for further investigation."

### Steps to reproduce

https://apex.oracle.com/pls/apex/f?p=4000:1500:1378771326703:::::]]]]

Step-1

Created the application ID -142230 on lower version -Apex 21.1 and then, created one sample flow which has a step to through Oracle PL/SQL errors. After that we created another version of the flow with different name of the step which is throwing Oracle Pl/SQL errors.

Step-2

Imported the same application with new id #42745 - with Apex version -22.1. Now, when clicking on the error step, it is showing the same issue which is highlighted as a bug.

### Expected behaviour

It should show Oracle PL/SQL error log

**Comment by satyaOracle** [comment] 2022-04-28 04:17
**Note -:** Existing flows in the application (creted on previous version), that had errors, are giving this issue.
The flows which are created in new version, if execution failed on those flows then errors are showing without any issues after clicking on the error steps.

**Comment by satyaOracle** [comment] 2022-04-28 04:30
<img width="861" alt="Screenshot 2022-04-28 at 9 51 28 AM" src="https://user-images.githubusercontent.com/104496192/165676733-b0961c59-f6a9-4f59-b849-a5fcb2bc9fb7.png">

**Comment by nielsdebr** [comment] 2022-04-28 08:02
Thanks for reporting this. Can you reproduce this behavior on apex.oracle.com (even though APEX 22.1 is installed there) and give us access so that we can start analyze this? Thanks.

**Comment by satyaOracle** [comment] 2022-05-04 09:16
Hi, Please find the details of reproduce of error -:

https://apex.oracle.com/pls/apex/f?p=4000:1500:1378771326703:::::]]]

UserName - bug454 
Password -qawsedrf

Step-1 
********
Created the application ID -142230 on lower version -Apex 21.1 and then, created one sample flow which has a step to through Oracle PL/SQL errors. After that we created another version of the flow with different name of the step which is throwing Oracle Pl/SQL errors.

 Step-2
*********
Imported the same application with new id #42745 - with Apex version -22.1. Now, when clicking on the error step, it is showing the same issue which is highlighted as a bug. 

Let me know if you need more details on the same.

**Comment by LouisMoreaux** [comment] 2022-05-04 09:36
Thank you for the step to reproduce, but we need to have the workspace name too.

**Comment by satyaOracle** [comment] 2022-05-04 09:48
> Thank you for the steps to reproduce, but we need to have the workspace name too.

Workspace Name - > Satya_ws2022

**Comment by LouisMoreaux** [comment] 2022-05-04 10:36
This issue is a duplicate of #436 which is already fixed and will be part of the next release.
Sorry for the inconvenience.

**Closed by LouisMoreaux** 2022-05-04 10:36 UTC
Labels: bug, duplicate
