### ISSUE TITLE
[bug]: Dark Mode: when you create a new Instance, it can't read the models name (white color font same as background)

### ISSUE THREAD

**Issue by devrebeleza** [flowsforapex/apex-flowsforapex#568] opened 2022-12-23 19:36 UTC
### Flows for APEX version

22.2 (latest)

### Oracle Database version

19c

### Oracle APEX version

22.1

### Have you used the BPMN-Linter in Flow Designer to Validate your Diagram?

Yes

### What happened?

When the user selects dark mode and wants to create a new instance, the model name color is white, the same as the background color.

Light Mode -> 
![Light mode example](https://user-images.githubusercontent.com/32907345/209397954-58a936e7-cb15-43ff-85f8-eaae6ab359f6.png)

Dark Mode -> 
![Dark mode doesn't show Models](https://user-images.githubusercontent.com/32907345/209398046-46325cd2-7739-4b55-97c1-17ccca1cccd0.png)

### Expected behaviour

Changing "CSS" - color:black

Dark Mode fixed ->
![Dark mode doesn't show Models - css modified](https://user-images.githubusercontent.com/32907345/209398183-59cd72fd-e1db-4407-a069-dc617f1dc318.png)

**Comment by LouisMoreaux** [comment] 2023-01-04 07:32
Hello,

Did you refresh the APEX Universal Theme for the Flows for APEX application? Because as we support APEX 20.1, you have to upgrade the theme regarding your current APEX version.

Regards,
Louis

**Comment by rallen2010** [comment] 2023-01-04 21:06
With Flows for APEX v22.2 Distribution on APEX 22.2 with the Theme NOT upgraded, I could replicate the problem on my system.   But after refreshing the Universal Theme to current release, the problem went away.  (Note you will need to do 2 steps to upgrade.   Firstly, update the Compatibility Mode - Shared Components > Application definition > Compatibility Mode -> set to '21.2 / 22.1 / 22.1'.  then 2) Click the Region top message advising you upgrade your Universal Theme.)

Please confirm that this solves YOUR problem.

**Comment by rallen2010** [comment] 2023-01-05 09:55
Closing as not a bug.

**Closed by rallen2010** 2023-01-05 09:55 UTC
Labels: engine-app, not a bug
