### ISSUE TITLE
[enhancement]: Migrating application to another server  

### ISSUE THREAD

**Issue by fahadrafique** [flowsforapex/apex-flowsforapex#439] opened 2022-03-07 10:04 UTC
### Flows for APEX version

21.1

### Oracle Database version

19

### Oracle APEX version

20.1

### What happened?

when we are transferring the application along with database to another environment production database then it is started throwing unique constraints errors and we cannot delete the sequences because you have created system sequences for entire application tables which can't be modified or delete to get the new sequence.

Do you have any script or feature available to copy the application and its database without having an issue of constraints?

### Steps to reproduce

N/A

### Expected behaviour

N/A

**Comment by LouisMoreaux** [comment] 2022-03-07 10:31
Hello,

We support export/import of models from one **Flows for APEX instance** to another to be able to move models from DEV to QA/TEST/PRODUCTION. This operation can be done using the application which is part of the distribution.

I am not sure of what you are expected here but if you are exporting the database and importing it into another instance (aka expdp/impdp) then Oracle should manage the identity columns for you and this is out of the scope of this project.

Please post more details and I will be happy to help you if the issue is when using the application or the PL/SQL API of Flows fro APEX.

Regards,
Louis

**Comment by commi235** [comment] 2022-07-15 13:29
Closing issue as no more feedback received.
Please get in contact with us if more help is needed.

**Closed by commi235** 2022-07-15 13:29 UTC
Labels: bug, question
